declaration:
  call: declare
  version: 0.1
  description: "Decription placeholder for 'ORGANIZATION-WORKING-TIME'"
  method: get
  accepts: json
  returns: json
  namespace: backoffice

getOrganizationWorkingTime:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]/get-organization-working-time"
  result: res

validateOrganizationWorkingTimeExists:
  switch:
    - condition: "${res.response.body.length > 0}"
      next: mapWorkingTimeData
  next: returnNotFound

mapWorkingTimeData:
  call: http.post
  args:
    url: "[#CHATBOT_DMAPPER_HBS]/return_organization_working_time"
    headers:
      type: json
    body:
      configurationArray: ${res.response.body}
  result: workingTimeData
  next: returnSuccess

returnSuccess:
  return: ${workingTimeData.response.body}
  next: end

returnUnauthorized:
  return: "error: unauthorized"
  next: end

returnNotFound:
  return: "error: not found"
  next: end
